enable-magisk-update = true
parallel-jobs = 1
compression-level = 9
riplib = true

[Morphe-YouTube]
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
patches-version = "latest"
cli-version = "dev"
app-name = "YouTube"
rv-brand = "Morphe"
build-mode = "both"
#dpi = "none"
arch = "arm64-v8a"
version = "21.06.254"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
included-patches = "'Disable Shorts on startup' 'Force premium heading' 'MaterialYou' 'Material You'"
excluded-patches = "'Custom branding icon for YouTube' 'Custom branding name for YouTube' 'Custom branding' 'Change start page' 'SponsorBlock' 'Return YouTube Dislike' 'Enable debug logging' 'Alternative thumbnails' 'Enable debugging'"

[Morphe-Music]
enabled = true
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
patches-version = "latest"
cli-version = "dev"
app-name = "Music"
#rv-brand = "Morphe"
build-mode = "both"
version = "9.06.51"
dpi = "120-480dpi"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
arch = "arm64-v8a"
excluded-patches = "'Certificate spoof' 'Custom branding' 'Custom branding icon for YouTube Music' 'Custom branding name for YouTube Music' 'Custom branding icon MMT' 'Custom branding icon Revancify Blue' 'Custom branding icon Revancify Red' 'Custom branding icon YouTube Music' 'Custom branding icon YouTube Music' 'Custom playback speed' 'Enable custom filter' 'Enable old style library shelf' 'Enable old style miniplayer' 'Enable zen mode' 'Hide category bar' 'Hide new playlist button' 'Hide playlist card' 'Hide radio button' 'Remember playback speed' 'Replace dismiss queue' 'Return YouTube Dislike' 'SponsorBlock 'Enable debugging' 'Translations'"


[GooglePhotos]
enabled = false
build-mode = "both"
patches-version=" v5.48.0"
arch = "arm64-v8a"
#version = "7.61.0.860908034"
version = "latest"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.photos"


[Morphe-Music-dev]
enabled = false
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
patches-version = "dev"
cli-version = "dev"
app-name = "Music"
rv-brand = "Morphe-dev"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
arch = "arm64-v8a"
included-patches = ""
excluded-patches = """\
    'Custom branding' \
    """

[Morphe-YouTube-dev]
enabled = false
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
patches-version = "dev"
cli-version = "dev"
app-name = "YouTube"
rv-brand = "Morphe-dev"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
included-patches = ""
excluded-patches = """\
    'Custom branding' \
    """

[anddea-Music-Extended]
enabled = false
patches-source = "anddea/revanced-patches"
cli-source = "MorpheApp/morphe-cli"
patches-version = "latest"
cli-version = "dev"
app-name = "Music"
rv-brand = "ReVanced Anddea"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
arch = "arm64-v8a"
included-patches = ""
excluded-patches = """\
    'Custom branding name for YouTube Music' \
    'Custom branding icon for YouTube Music' \
    """

[anddea-YouTube-Extended]
enabled = false
patches-source = "anddea/revanced-patches"
cli-source = "MorpheApp/morphe-cli"
patches-version = "latest"
cli-version = "dev"
app-name = "YouTube"
rv-brand = "ReVanced Anddea"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
included-patches = ""
excluded-patches = """\
    'Custom branding name for YouTube' \
    'Custom branding icon for YouTube' \
    """

[anddea-Music-Extended-dev]
enabled = false
patches-source = "anddea/revanced-patches"
cli-source = "MorpheApp/morphe-cli"
patches-version = "dev"
cli-version = "dev"
app-name = "Music"
rv-brand = "ReVanced Anddea-dev"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
arch = "arm64-v8a"
included-patches = ""
excluded-patches = """\
    'Custom branding name for YouTube Music' \
    'Custom branding icon for YouTube Music' \
    """

[anddea-YouTube-Extended-dev]
enabled = false
patches-source = "anddea/revanced-patches"
cli-source = "MorpheApp/morphe-cli"
patches-version = "dev"
cli-version = "dev"
app-name = "YouTube"
rv-brand = "ReVanced Anddea-dev"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
included-patches = ""
excluded-patches = """\
    'Custom branding name for YouTube' \
    'Custom branding icon for YouTube' \
    """

