enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 4

[GooglePhotos]
build-mode = "both"
patches-version=" v5.48.0"
arch = "arm64-v8a"
version = "7.61.0.860908034"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.photos"
